# Generated by Django 5.1.7 on 2025-04-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Hisse Adı")),
                (
                    "symbol",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Hisse Sembolü"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Sektör"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
            ],
            options={
                "verbose_name": "Hisse",
                "verbose_name_plural": "Hisseler",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="StockAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Analiz Tarihi")),
                (
                    "moving_average_50",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="50 Günlük Ortalama",
                    ),
                ),
                (
                    "moving_average_200",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="200 Günlük Ortalama",
                    ),
                ),
                (
                    "rsi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="RSI",
                    ),
                ),
                (
                    "macd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="MACD",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="Tahmin.stock",
                        verbose_name="Hisse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hisse Analizi",
                "verbose_name_plural": "Hisse Analizleri",
                "ordering": ["-date"],
                "unique_together": {("stock", "date")},
            },
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                (
                    "opening_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Açılış Fiyatı"
                    ),
                ),
                (
                    "closing_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Kapanış Fiyatı"
                    ),
                ),
                (
                    "highest_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="En Yüksek Fiyat"
                    ),
                ),
                (
                    "lowest_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="En Düşük Fiyat"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="İşlem Hacmi")),
                (
                    "daily_change",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Günlük Değişim (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="Tahmin.stock",
                        verbose_name="Hisse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hisse Fiyatı",
                "verbose_name_plural": "Hisse Fiyatları",
                "ordering": ["-date"],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
