# Generated by Django 5.1.7 on 2025-04-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tahmin", "0002_stockfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockfile",
            name="error_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stockfile",
            name="error_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockfile",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockfile",
            name="success_count",
            field=models.IntegerField(default=0),
        ),
    ]
