# Generated by Django 5.1.7 on 2025-05-13 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tahmin", "0004_rename_moving_average_200_stockanalysis_ma_200_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Model Adı")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Model Açıklaması"
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        default="hybrid", max_length=50, verbose_name="Model Tipi"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Model Parametreleri"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tahmin Modeli",
                "verbose_name_plural": "Tahmin Modelleri",
            },
        ),
        migrations.CreateModel(
            name="StockPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_date", models.DateTimeField(verbose_name="Tahmin Tarihi")),
                (
                    "time_horizon",
                    models.IntegerField(default=12, verbose_name="Zaman Ufku (Ay)"),
                ),
                ("last_price", models.FloatField(verbose_name="Son Fiyat")),
                (
                    "predicted_price",
                    models.FloatField(verbose_name="Tahmin Edilen Fiyat"),
                ),
                (
                    "percent_change",
                    models.FloatField(verbose_name="Değişim Yüzdesi (%)"),
                ),
                (
                    "lower_bound",
                    models.FloatField(blank=True, null=True, verbose_name="Alt Sınır"),
                ),
                (
                    "upper_bound",
                    models.FloatField(blank=True, null=True, verbose_name="Üst Sınır"),
                ),
                (
                    "confidence_level",
                    models.FloatField(default=0.95, verbose_name="Güven Düzeyi"),
                ),
                (
                    "prediction_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Tahmin Verileri"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="Tahmin.predictionmodel",
                        verbose_name="Model",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="Tahmin.stock",
                        verbose_name="Hisse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hisse Tahmini",
                "verbose_name_plural": "Hisse Tahminleri",
                "ordering": ["-prediction_date"],
            },
        ),
        migrations.CreateModel(
            name="PredictionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        default="detailed", max_length=50, verbose_name="Rapor Tipi"
                    ),
                ),
                ("html_content", models.TextField(verbose_name="HTML İçeriği")),
                (
                    "charts_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Grafik Verileri"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "report_path",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Rapor Dosya Yolu",
                    ),
                ),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="Tahmin.stockprediction",
                        verbose_name="Tahmin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tahmin Raporu",
                "verbose_name_plural": "Tahmin Raporları",
                "ordering": ["-created_at"],
            },
        ),
    ]
