# Generated by Django 5.1.7 on 2025-05-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Tahmin", "0005_predictionmodel_stockprediction_predictionreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockprediction",
            name="model",
        ),
        migrations.RemoveField(
            model_name="predictionreport",
            name="prediction",
        ),
        migrations.RemoveField(
            model_name="stockprediction",
            name="stock",
        ),
        migrations.DeleteModel(
            name="PredictionModel",
        ),
        migrations.DeleteModel(
            name="PredictionReport",
        ),
        migrations.DeleteModel(
            name="StockPrediction",
        ),
    ]
