# Generated by Django 5.1.7 on 2025-05-14 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tahmin", "0006_remove_stockprediction_model_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MacroeconomicData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                (
                    "tufe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="TÜFE Aylık (%)",
                    ),
                ),
                (
                    "tufe_yillik",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="TÜFE Yıllık (%)",
                    ),
                ),
                (
                    "ufe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="ÜFE Aylık (%)",
                    ),
                ),
                (
                    "ufe_yillik",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="ÜFE Yıllık (%)",
                    ),
                ),
                (
                    "policy_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="TCMB Politika Faizi (%)",
                    ),
                ),
                (
                    "bond_yield_2y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="2 Yıllık Tahvil Faizi (%)",
                    ),
                ),
                (
                    "bond_yield_10y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="10 Yıllık Tahvil Faizi (%)",
                    ),
                ),
                (
                    "usd_try",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="USD/TRY",
                    ),
                ),
                (
                    "eur_try",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="EUR/TRY",
                    ),
                ),
                (
                    "gdp_growth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="GSYH Büyüme (%)",
                    ),
                ),
                (
                    "unemployment_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="İşsizlik Oranı (%)",
                    ),
                ),
                (
                    "bist100_close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="BIST 100 Kapanış",
                    ),
                ),
                (
                    "bist100_change",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="BIST 100 Değişim (%)",
                    ),
                ),
                (
                    "market_volume",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Piyasa İşlem Hacmi (TL)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Makroekonomik Veri",
                "verbose_name_plural": "Makroekonomik Veriler",
                "ordering": ["-date"],
                "get_latest_by": "date",
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Sektör Adı")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Sektör Kodu"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
            ],
            options={
                "verbose_name": "Sektör",
                "verbose_name_plural": "Sektörler",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SentimentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                (
                    "sentiment_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Duygu Skoru (-1 ila 1)",
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        choices=[
                            ("VERY_POSITIVE", "Çok Olumlu"),
                            ("POSITIVE", "Olumlu"),
                            ("NEUTRAL", "Nötr"),
                            ("NEGATIVE", "Olumsuz"),
                            ("VERY_NEGATIVE", "Çok Olumsuz"),
                        ],
                        max_length=15,
                        verbose_name="Duygu Etiketi",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("TWITTER", "Twitter"),
                            ("NEWS", "Haber"),
                            ("FORUM", "Forum"),
                            ("ANALYST", "Analist"),
                            ("OTHER", "Diğer"),
                        ],
                        max_length=10,
                        verbose_name="Kaynak",
                    ),
                ),
                (
                    "content_sample",
                    models.TextField(
                        blank=True, null=True, verbose_name="İçerik Örneği"
                    ),
                ),
                (
                    "mention_count",
                    models.IntegerField(default=0, verbose_name="Bahsedilme Sayısı"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiments",
                        to="Tahmin.stock",
                        verbose_name="Hisse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Duygu Analizi",
                "verbose_name_plural": "Duygu Analizleri",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CompanyFinancial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("Q1", "1. Çeyrek"),
                            ("Q2", "2. Çeyrek"),
                            ("Q3", "3. Çeyrek"),
                            ("Q4", "4. Çeyrek"),
                            ("ANNUAL", "Yıllık"),
                        ],
                        max_length=10,
                        verbose_name="Dönem",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Yıl")),
                (
                    "revenue",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Satış Geliri (TL)"
                    ),
                ),
                (
                    "ebitda",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="FAVÖK (TL)"
                    ),
                ),
                (
                    "net_income",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Net Kar (TL)"
                    ),
                ),
                (
                    "total_assets",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Toplam Varlıklar (TL)"
                    ),
                ),
                (
                    "total_liabilities",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Toplam Yükümlülükler (TL)"
                    ),
                ),
                (
                    "equity",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Özkaynaklar (TL)"
                    ),
                ),
                (
                    "debt_to_equity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Borç/Özsermaye",
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="ROE (%)",
                    ),
                ),
                (
                    "eps",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Hisse Başı Kazanç (TL)",
                    ),
                ),
                (
                    "dividend",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Temettü (TL)",
                    ),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Temettü Verimi (%)",
                    ),
                ),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="F/K Oranı",
                    ),
                ),
                (
                    "pb_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="PD/DD",
                    ),
                ),
                (
                    "ev_ebitda",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="FD/FAVÖK",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financials",
                        to="Tahmin.stock",
                        verbose_name="Hisse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Şirket Finansalı",
                "verbose_name_plural": "Şirket Finansalları",
                "ordering": ["-year", "-period"],
                "unique_together": {("stock", "period", "year")},
            },
        ),
        migrations.CreateModel(
            name="SectorIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Endeks Değeri"
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Günlük Değişim (%)",
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="İşlem Hacmi")),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indices",
                        to="Tahmin.sector",
                        verbose_name="Sektör",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sektör Endeksi",
                "verbose_name_plural": "Sektör Endeksleri",
                "ordering": ["-date"],
                "unique_together": {("sector", "date")},
            },
        ),
    ]
