# Generated by Django 5.1.7 on 2025-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tahmin", "0007_macroeconomicdata_sector_sentimentdata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InflationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("Ocak", "Ocak"),
                            ("Şubat", "Şubat"),
                            ("Mart", "Mart"),
                            ("Nisan", "Nisan"),
                            ("Mayıs", "Mayıs"),
                            ("Haziran", "Haziran"),
                            ("Temmuz", "Temmuz"),
                            ("Ağustos", "Ağustos"),
                            ("Eylül", "Eylül"),
                            ("Ekim", "Ekim"),
                            ("Kasım", "Kasım"),
                            ("Aralık", "Aralık"),
                        ],
                        max_length=10,
                        verbose_name="Ay",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Yıl")),
                (
                    "tufe_monthly",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="TÜFE Aylık (%)"
                    ),
                ),
                (
                    "tufe_yearly",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="TÜFE Yıllık (%)"
                    ),
                ),
                (
                    "ufe_monthly",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="ÜFE Aylık (%)"
                    ),
                ),
                (
                    "ufe_yearly",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="ÜFE Yıllık (%)"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="TÜİK", max_length=50, verbose_name="Veri Kaynağı"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Enflasyon Verisi",
                "verbose_name_plural": "Enflasyon Verileri",
                "ordering": ["-year", "month"],
                "unique_together": {("month", "year")},
            },
        ),
    ]
