# Generated by Django 5.1.7 on 2025-05-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tahmin", "0008_inflationdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                (
                    "policy_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="TCMB Politika Faizi (%)",
                    ),
                ),
                (
                    "bond_yield_2y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="2 Yıllık Tahvil Faizi (%)",
                    ),
                ),
                (
                    "bond_yield_10y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="10 Yıllık Tahvil Faizi (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Faiz Oranı",
                "verbose_name_plural": "Faiz Oranları",
                "ordering": ["-date"],
                "get_latest_by": "date",
            },
        ),
    ]
