# Generated by Django 5.1.7 on 2025-05-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tahmin", "0009_interestrate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "Amerikan Doları"), ("EUR", "Euro")],
                        max_length=3,
                        verbose_name="Para Birimi",
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Açılış"
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="En Yüksek"
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="En Düşük"
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Kapanış"
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Hacim"
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Değişim (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Döviz Kuru",
                "verbose_name_plural": "Döviz Kurları",
                "ordering": ["-date", "currency"],
                "unique_together": {("date", "currency")},
            },
        ),
    ]
