# Generated by Django 5.1.7 on 2025-05-15 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tahmin", "0010_exchangerate"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyfinancial",
            name="excel_path",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Excel Dosyası Yolu"
            ),
        ),
        migrations.AddField(
            model_name="companyfinancial",
            name="extra_data",
            field=models.TextField(
                blank=True, null=True, verbose_name="Analiz Sonuçları (JSON)"
            ),
        ),
        migrations.AddField(
            model_name="companyfinancial",
            name="pdf_path",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="PDF Dosyası Yolu"
            ),
        ),
        migrations.CreateModel(
            name="SectoralRegulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("announcement_date", models.DateField(verbose_name="Duyuru Tarihi")),
                ("effective_date", models.DateField(verbose_name="Yürürlük Tarihi")),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("VERY_POSITIVE", "Çok Olumlu"),
                            ("POSITIVE", "Olumlu"),
                            ("NEUTRAL", "Nötr"),
                            ("NEGATIVE", "Olumsuz"),
                            ("VERY_NEGATIVE", "Çok Olumsuz"),
                        ],
                        max_length=15,
                        verbose_name="Etki",
                    ),
                ),
                ("source", models.CharField(max_length=200, verbose_name="Kaynak")),
                (
                    "source_url",
                    models.URLField(blank=True, null=True, verbose_name="Kaynak URL"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notlar"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eklenme Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regulations",
                        to="Tahmin.sector",
                        verbose_name="Sektör",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sektörel Regülasyon",
                "verbose_name_plural": "Sektörel Regülasyonlar",
                "ordering": ["-announcement_date", "sector"],
            },
        ),
        migrations.CreateModel(
            name="SeasonalEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("WINTER", "Kış"),
                            ("SPRING", "İlkbahar"),
                            ("SUMMER", "Yaz"),
                            ("AUTUMN", "Sonbahar"),
                            ("QUARTER_1", "1. Çeyrek"),
                            ("QUARTER_2", "2. Çeyrek"),
                            ("QUARTER_3", "3. Çeyrek"),
                            ("QUARTER_4", "4. Çeyrek"),
                            ("RAMADAN", "Ramazan"),
                            ("EID", "Bayram"),
                            ("NEW_YEAR", "Yılbaşı"),
                            ("SUMMER_HOLIDAY", "Yaz Tatili"),
                            ("OTHER", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Mevsim/Dönem",
                    ),
                ),
                (
                    "effect",
                    models.CharField(
                        choices=[
                            ("VERY_POSITIVE", "Çok Olumlu"),
                            ("POSITIVE", "Olumlu"),
                            ("NEUTRAL", "Nötr"),
                            ("NEGATIVE", "Olumsuz"),
                            ("VERY_NEGATIVE", "Çok Olumsuz"),
                        ],
                        max_length=15,
                        verbose_name="Etki",
                    ),
                ),
                (
                    "effect_description",
                    models.TextField(verbose_name="Etki Açıklaması"),
                ),
                (
                    "average_change",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Ortalama Değişim (%)",
                    ),
                ),
                (
                    "historical_data",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tarihsel Veri Özeti"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notlar"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eklenme Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_effects",
                        to="Tahmin.sector",
                        verbose_name="Sektör",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mevsimsel Etki",
                "verbose_name_plural": "Mevsimsel Etkiler",
                "ordering": ["sector", "season"],
                "unique_together": {("sector", "season")},
            },
        ),
        migrations.CreateModel(
            name="SectoralGrowth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Yıl")),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("Q1", "1. Çeyrek"),
                            ("Q2", "2. Çeyrek"),
                            ("Q3", "3. Çeyrek"),
                            ("Q4", "4. Çeyrek"),
                            ("ANNUAL", "Yıllık"),
                        ],
                        max_length=10,
                        verbose_name="Dönem",
                    ),
                ),
                (
                    "growth_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Büyüme Oranı (%)"
                    ),
                ),
                (
                    "volume",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Hacim (TL)"
                    ),
                ),
                (
                    "employment_change",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="İstihdam Değişimi (%)",
                    ),
                ),
                (
                    "export_growth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="İhracat Büyümesi (%)",
                    ),
                ),
                (
                    "investment_growth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Yatırım Büyümesi (%)",
                    ),
                ),
                (
                    "source",
                    models.CharField(max_length=200, verbose_name="Veri Kaynağı"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notlar"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Eklenme Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growth_data",
                        to="Tahmin.sector",
                        verbose_name="Sektör",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sektörel Büyüme Verisi",
                "verbose_name_plural": "Sektörel Büyüme Verileri",
                "ordering": ["-year", "-period", "sector"],
                "unique_together": {("sector", "year", "period")},
            },
        ),
        migrations.CreateModel(
            name="SectoralIndexData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                (
                    "open_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Açılış Değeri"
                    ),
                ),
                (
                    "high_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="En Yüksek Değer"
                    ),
                ),
                (
                    "low_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="En Düşük Değer"
                    ),
                ),
                (
                    "close_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Kapanış Değeri"
                    ),
                ),
                (
                    "volume",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="İşlem Hacmi"
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Değişim (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_data",
                        to="Tahmin.sector",
                        verbose_name="Sektör",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sektör Endeks Verisi",
                "verbose_name_plural": "Sektör Endeks Verileri",
                "ordering": ["-date", "sector"],
                "unique_together": {("date", "sector")},
            },
        ),
    ]
